# Generated by Django 3.2.5 on 2023-09-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='image',
            field=models.ImageField(default='', upload_to='avatars'),
        ),
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(default='Имя', max_length=200),
        ),
        migrations.AddField(
            model_name='users',
            name='surname',
            field=models.CharField(default='Фамилия', max_length=200),
        ),
    ]
