# Generated by Django 3.2.5 on 2023-09-30 15:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_auto_20230930_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Название файла', max_length=300)),
                ('file', models.FileField(upload_to='files_users/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mp3', 'png', 'jpg'])])),
                ('name_type', models.CharField(default='TYPE', max_length=100)),
                ('size', models.CharField(default='SIZE', max_length=200)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
