# Generated by Django 3.2.5 on 2023-09-30 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='id_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authorization.users'),
        ),
    ]
